package SimulationInterface;

import Sensor.*;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class SimulationValueFrame extends JFrame{

    private Sensor sensor;

    private JFrame window;
    /**
     * Creates new form SimulationValueFrame
     */
    public SimulationValueFrame(Sensor sensor) {
        initComponents();
        this.sensor=sensor;
        window=new JFrame();
        window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        window.setSize(589, 300);
        window.add(this);
        window.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        int[] intervale=new int[2];
        intervale=this.sensor.getSensorType().getInterval();
        dataType = new javax.swing.ButtonGroup();
        slipter1 = new javax.swing.JSeparator();
        id = new javax.swing.JLabel();
        loc = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        interBegin = new javax.swing.JLabel();
        interMin = new javax.swing.JLabel();
        comma = new javax.swing.JLabel();
        interMax = new javax.swing.JLabel();
        interEnd = new javax.swing.JLabel();
        spliter2 = new javax.swing.JSeparator();
        data = new javax.swing.JLabel();
        rnd = new javax.swing.JRadioButton();
        fix = new javax.swing.JRadioButton();
        connectFrame = new javax.swing.JButton();
        dataValue = new javax.swing.JTextField();
        frequency = new javax.swing.JLabel();
        freqValue = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        id.setText(this.sensor.getId());

        loc.setText("location");

        type.setText(this.sensor.getSensorType().toString());

        interBegin.setText("Intervalle de données : [ ");

        interMin.setText(""+intervale[0]);

        comma.setText(",");
        //
        interMax.setText(""+intervale[1]);

        interEnd.setText("]");

        data.setText("Données : ");

        dataType.add(rnd);
        rnd.setText("Aléatoire");
        rnd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rndMouseClicked(evt);
            }
        });
        rnd.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                rndComponentHidden(evt);
            }
        });
        rnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rndActionPerformed(evt);
            }
        });

        dataType.add(fix);
        fix.setText("Fixe");
        fix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixActionPerformed(evt);
            }
        });

        connectFrame.setText("Envoie de donnèes");

        dataValue.setText("Valeur de la données");
        dataValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataValueActionPerformed(evt);
            }
        });

        frequency.setText("Frequence :");

        freqValue.setText("Valeur de la fréquence");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(slipter1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(id)
                                .addGap(104, 104, 104)
                                .addComponent(loc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(type)
                                .addGap(75, 75, 75))
                        .addComponent(spliter2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(99, 99, 99)
                                                .addComponent(interBegin)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(interMin)
                                                .addGap(18, 18, 18)
                                                .addComponent(comma)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(interMax)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(interEnd))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(246, 246, 246)
                                                .addComponent(connectFrame)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(frequency)
                                        .addComponent(data))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(fix)
                                                .addGap(44, 44, 44)
                                                .addComponent(rnd))
                                        .addComponent(dataValue)
                                        .addComponent(freqValue))
                                .addGap(131, 131, 131))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(loc)
                                        .addComponent(type)
                                        .addComponent(id))
                                .addGap(18, 18, 18)
                                .addComponent(slipter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(interBegin)
                                        .addComponent(interMin)
                                        .addComponent(comma)
                                        .addComponent(interMax)
                                        .addComponent(interEnd))
                                .addGap(18, 18, 18)
                                .addComponent(spliter2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rnd)
                                        .addComponent(fix)
                                        .addComponent(data))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dataValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(frequency)
                                        .addComponent(freqValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(connectFrame)
                                .addGap(124, 124, 124))
        );
    }// </editor-fold>

    private void dataValueActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void rndMouseClicked(java.awt.event.MouseEvent evt) {
        dataValue.setVisible(false);
    }

    private void rndActionPerformed(java.awt.event.ActionEvent evt) {
        dataValue.setEditable(false);
        dataValue.setVisible(false);
    }

    private void rndComponentHidden(java.awt.event.ComponentEvent evt) {
        // TODO add your handling code here:
    }

    private void fixActionPerformed(java.awt.event.ActionEvent evt) {
        dataValue.setEditable(true);
        dataValue.setVisible(true);
    }


    // Variables declaration - do not modify
    private javax.swing.JLabel comma;
    private javax.swing.JButton connectFrame;
    private javax.swing.JLabel data;
    private javax.swing.ButtonGroup dataType;
    private javax.swing.JTextField dataValue;
    private javax.swing.JRadioButton fix;
    private javax.swing.JTextField freqValue;
    private javax.swing.JLabel frequency;
    private javax.swing.JLabel id;
    private javax.swing.JLabel interBegin;
    private javax.swing.JLabel interEnd;
    private javax.swing.JLabel interMax;
    private javax.swing.JLabel interMin;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel loc;
    private javax.swing.JRadioButton rnd;
    private javax.swing.JSeparator slipter1;
    private javax.swing.JSeparator spliter2;
    private javax.swing.JLabel type;
    // End of variables declaration
}
